apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: belugaga-com-tls
spec:
  secretName: belugaga-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: belugaga.com
  dnsNames:
    - belugaga.com
    - www.belugaga.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - belugaga.com
          - www.belugaga.com